import Navbar from '@/components/navbar'
import MaxWidthWrapper from '@/components/ui/max-width-wrapper'
import { cn } from '@/lib/utils'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'h-screen w-full text-base antialiased',
          GeistSans.className,
        )}
      >
        <MaxWidthWrapper>
          <Navbar />
        </MaxWidthWrapper>
        {children}
      </body>
    </html>
  )
}
